### ISSUE TITLE
Ensure kwargs injections work properly with rubinius

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-auto_inject#18]
Right now they are broken due to https://github.com/rubinius/rubinius/issues/3538. When this bug is fixed (a PR is underway at https://github.com/rubinius/rubinius/pull/3650), we can ensure the tests all pass on rbx again and put it back in the matrix of required platforms on Travis.

**Comment by flash-gordon** [comment]
okay, this one is stale, we don't support rubinius anymore since it's not worth the effort 😞
