### ISSUE TITLE
Best place to ask questions

### ISSUE THREAD

**Issue by jmgarnier** [dry-rb/dry-auto_inject#28]
Hi,

I am not sure where to ask:
- issues
- discourse
- or Gitter?

Here is my question 😉 : https://discuss.dry-rb.org/t/examples-of-how-to-use-dry-container-dry-auto-inject/82?u=jmgarnier

Thanks for the libraries & blog posts anyway 🙇 I can't wait before trying `dry-transactions` and `dry-monad`!

**Comment by timriley** [comment]
https://discuss.dry-rb.org is the best place to ask support questions! I see your question already has a response there now, please do reply over there if you need more help :)

**Comment by apohllo** [comment]
https://discuss.dry-rb.org/ is no longer available. The valid address is https://discourse.dry-rb.org/
