### ISSUE TITLE
Inheritance broken

### ISSUE THREAD

**Issue by apotonick** [dry-rb/dry-auto_inject#29]
```ruby
class A
  def initialize(args)
    super
  end
end

class B < A
  include AutoInject[:user_repository]
end

B.new({})
```

This leads to the following exception.

```
`initialize': wrong number of arguments (0 for 1) (ArgumentError)
	from /home/nick/.rvm/gems/ruby-2.2.3/gems/dry-auto_inject-0.4.1/lib/dry/auto_inject/strategies/kwargs.rb:61:in `initialize'
	from /home/nick/.rvm/gems/ruby-2.2.3/gems/dry-auto_inject-0.4.1/lib/dry/auto_inject/strategies/kwargs.rb:17:in `new'
	from /home/nick/.rvm/gems/ruby-2.2.3/gems/dry-auto_inject-0.4.1/lib/dry/auto_inject/strategies/kwargs.rb:17:in `new'
```

This only happens with `B`, not with `A`.

**Comment by timriley** [comment]
The error message isn't particularly helpful here, sorry about that, but I think this might just be an issue with the class design?

The default strategy for an injection with the recent dry-auto_inject releases is `kwargs`, which means it expects the constructors to accept kwarg arguments.

So, if I arrange an example like this, everything works:

```ruby
AutoInject = Dry::AutoInject({user_repository: "hi"})

class A
  def initialize(user_repository:)
    @user_repository = user_repository
  end
end

class B < A
  include AutoInject[:user_repository]
end

B.new
# => #<B:0x007fa3f3d68e60 @user_repository="hi">
```

If you wanted to just have a single non-keyword argument, like in the code you posted, you'd need to do the following:

```
```

**Comment by apotonick** [comment]
Thanks Tim, so the strategy is "inferred" from the `initialize` arugment signature?

**Comment by timriley** [comment]
The injection strategy isn't inferred at all (I think that'd be hard to get right and potentially confusing), you just provide it when you include the injection mixin, e.g.


```ruby
Inject = Dry::AutoInject(container)

class A
  include Inject["foo"] # default strategy, kwargs
end

class B
  include Inject.hash["foo"] # hash strategy, for initializers expecting an options hash
end

class C
  include Inject.args["foo"] # positional args strategy
end
```

This means you can also set a particular strategy for your application's default, if you like, but then also choose another one in a particular context, e.g.

```ruby
# Use positional args by default
Inject = Dry::AutoInject(container).args

# But switch to hash strategy for this class only
class D
  include Inject.hash["foo"]
end
```

**Comment by apotonick** [comment]
Interesting, with `inititialize(**options)` it works, as you said. Thanks! May I ask why/how you treat `options` and `**options` differently? Or is that me not understanding the new `**` splash?

**Comment by flash-gordon** [comment]
@apotonick it looks differently when you introspect it with `Method#parameters`
```
2.3.0 :001 > def foo(options); end
 => :foo
2.3.0 :002 > def bar(**options); end
 => :bar
2.3.0 :003 > method(:foo).parameters
 => [[:req, :options]]
2.3.0 :004 > method(:bar).parameters
 => [[:keyrest, :options]]
```
https://github.com/dry-rb/dry-auto_inject/search?utf8=%E2%9C%93&q=parameters

**Comment by timriley** [comment]
Yeah, so the new `**args` splat works like `*args` excepts it casts the arbitrary number of arguments into a hash instead of an array, since it works with keyword arguments. `options` (or even just `args`) on its own is just a regular single positional argument, which accepts just a single object, and it only so happens to work with a hash of options by convention (and by Ruby's convenient behaviour of allowing the hash literal syntax to be dropped for the final argument of a method call).
