### ISSUE TITLE
Allow aliasing of registered classes using AutoInject

### ISSUE THREAD

**Issue by adaam2** [dry-rb/dry-auto_inject#36]
I have two namespaces (let's say `bill` and `bob`), both of which have a service named `service` registered in the `container`. If I want to use `Registry::AutoInject["bill.service", "bob.service"]` I receive the error `Dry::AutoInject::DuplicateDependencyError: name +service+ is already used`. 

If there are multiple dependencies using the same name, can we not prefix them with the namespace name (`bob_service` and `bill_service`) when injecting them into a class?

**Comment by flash-gordon** [comment]
@adaam2 you can set up aliases with
```ruby
Registry::AutoInject[bill_service: "bill.service", bob_service: "bob.service"]
```

**Comment by adaam2** [comment]
@flash-gordon Perfect, thanks
