### ISSUE TITLE
Interactions with dry-initializer

### ISSUE THREAD

**Issue by kbacha** [dry-rb/dry-auto_inject#40]
I was trying to implement this but it feels like it doesn't play that nice with other constructors or initializers. Is there more documentation on how this is supposed to function?

**Comment by solnic** [comment]
For support questions please start a thread on [discourse.dry-rb.org](https://discourse.dry-rb.org). See [reporting issue guidelines](https://github.com/dry-rb/dry-auto_inject/blob/master/CONTRIBUTING.md#issue-guidelines) for more information.
