### ISSUE TITLE
v0.5.0 breaks isolation tests with minitest mocks

### ISSUE THREAD

**Issue by TiteiKo** [dry-rb/dry-auto_inject#49]
```ruby
class Foobar
  include Inject[foo: 'bar']

  def do_something
    foo.do_something
    # ....
  end
end

# would be tested like this

class FoobarTest < Minitest::Test
  def test_it_calls_do_something_of_foo
    mock = Minitest::Mock.new
    mock.expect :do_something
    Foobar.new(foo: mock).do_something
    assert_mocked mock
  end
end
```

This was working fine before 0.5.0. Now, it gets the error `unmocked method :nil?, expected one of [:do_something]` due to https://github.com/dry-rb/dry-auto_inject/commit/193ed4891c556bb8bb75561cc40a64d8cf87883d#diff-f6dd1c9acc3de0d2ccbed1741aa38257, thus rendering mocking non straightforward

**Comment by timriley** [comment]
Thanks for raising this, @TiteiKo. I've adjusted some code in a currently-open PR (#48) to fix this issue.
