### ISSUE TITLE
Incompatibility with ActiveRecord

### ISSUE THREAD

**Issue by RomainEndelin** [dry-rb/dry-auto_inject#60]
Hello, thanks for the great DRY libs.
However, when trying to use `dry-auto_inject` with `ActiveRecord`, the container isn't injected properly on `MyModel.first`, `MyModel.find`, etc.

Unfortunately, I haven't been able to identify the root cause. But I have published a minimal working example here: https://github.com/RomainEndelin/dry_auto_inject_active_record_incompatibility

```ruby
irb(main):001:0> User.new.hello
=> "world"
irb(main):002:0> User.first.hello
  User Load (0.2ms)  SELECT  "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT ?  [["LIMIT", 1]]
=> nil
```

**Comment by solnic** [comment]
I'm sorry but this will not be supported, and even if it somehow starts working, it's **not recommended**. ActiveRecord is known for its bloated API, using DI and injecting even more stuff into your active record objects is not a good idea. DI is great for objects that are decoupled from the database in general.

**Comment by RomainEndelin** [comment]
Makes sense, thanks for the explanation.

**Comment by flash-gordon** [comment]
ActiveRecord uses `Class#allocate` while loading objects from DB, this bypasses initializers generated by dry-auto_inject. In a sense, these gems aren't compatible on a fundamental level.
