### ISSUE TITLE
Respect the container's `namespace_separator` when making local names for dependencies

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-auto_inject#8]
Right now we're presuming the namespace separator is a `"."`, but since this is configurable on dry-container, we should probably respect different separators.

The trick will be to work out an approach to this that still allows auto_inject to be "container agnostic" – ideally we don't do anything that _requires_ dry-container to be used at all times.

**Comment by michaelherold** [comment]
I took a crack at this in #23.

**Comment by timriley** [comment]
Closing this, explanation over in #23.
