### ISSUE TITLE
Injecting 2 containers causes ArgumentError

### ISSUE THREAD

**Issue by kroolp** [dry-rb/dry-auto_inject#83]
For the following code:
```ruby
class Foo
  def initialize(param)
  end
end

class Bar < Foo
  include AutoInject_1[:method_1]
  include AutoInject_2[:method_2]
end

Bar.new('test')
```
I get:
```ruby
ArgumentError:
       wrong number of arguments (given 2, expected 1)
```

It's because only one dependencies parameter is removed in the `initialize` method, so the base class is initialized by `super('test', method_1: ...)` instead of `super('test')`

## My environment

- Affects my production application: **NO**
- Ruby version: 3.0.3

**Comment by solnic** [comment]
To be honest, this seems like an edge case. Using multiple injection modules in the same class isn't an intended usage. It shouldn't cause an exception though. Maybe we should just raise a meaningful error that a given class already has a constructor defined by the injection module?

@timriley have you considered such a use case? Would you agree that we shouldn't support more than one injection module?

**Comment by kroolp** [comment]
Right, I thought the same, when I was looking into the code that it's not prepared for using multiple injections.
In my company, we use multiple containers and it helps to separate dependents from different subdomains.
It had worked fine to the moment when we needed a base class with some parameters in the constructor.

My proposition of the solution is not perfect, not working in each case, but I'll wait what is your decision about using multiple injections.

**Comment by kroolp** [comment]
Hi, as you said, such behavior is not expected, so I'm closing the issue.
