### ISSUE TITLE
Can't include in a class with already defined constructor

### ISSUE THREAD

**Issue by daniels** [dry-rb/dry-auto_inject#9]
Maybe it's an anti-pattern, but I'd like my classes being usable without any container or injector being ready. It used to work to include the injector in an existing class like so:

```ruby
class Foo
  attr_reader :foo
  def initialize(foo)
    @foo = foo
  end
end

Foo.new("local foo").foo # => "local foo"

container = { foo: "container foo"}
injector = Dry::AutoInject(container)
Foo.include(injector[:foo])

Foo.new.foo  # => "container foo"
```

But now it fails on `include` with:
```
# ~> NoMethodError
# ~> undefined method `parameters' for nil:NilClass
```

Seems like Dry::AutoInject::super_method returns nil if the method (`#initialize` in this case) is defined, and this is not checked for.

I'm not sure my use case is very strong, but I like seeing the use of AutoInject as a configuration detail.

**Comment by timriley** [comment]
Thanks @daniels. This might be related to some changes I made recently to have it work better with class inheritance. I'll see if there's a way to fix this.

**Comment by timriley** [comment]
@daniels I just made some changes and added a (passing) integration test to match your example. Would you mind trying this again?
